"""Evidence-first problem intelligence domain."""

from .benchmark import BenchmarkCase, BenchmarkValidationError, load_benchmark
from .cluster_benchmark import (
    ClusteringBenchmarkCase,
    evaluate_exact_clustering,
    load_clustering_benchmark,
)
from .clustering import ClusteringResult, cluster_exact, observation_fingerprint
from .connectors import JsonlFileConnector, SourceConnector, SourceDescriptor, SourceItemInput
from .domain import (
    ActorEquivalence,
    ClaimKind,
    Competitor,
    CompetitorComplaint,
    CompetitorEvidenceRole,
    CounterEvidenceItem,
    CounterEvidenceType,
    DachAssessment,
    DachTransferType,
    EvidenceCitation,
    EvidenceScope,
    EvidenceState,
    LocalEvidenceState,
    ObservationRecord,
    OpportunityClaimRole,
    OpportunityRecord,
    OpportunityStatus,
    OpportunityType,
    PipelineStage,
    PipelineStatus,
    ProblemType,
    RequirementProgress,
    RequirementStatus,
    ResearchCaseReportData,
    ResearchCaseStatus,
    ResearchCaseSummary,
    ResearchRequirement,
    SolutionType,
    SourceItemRecord,
    SourceLifecycle,
    WorkflowEquivalence,
)
from .evaluation import BenchmarkPrediction, evaluate_predictions, load_predictions
from .extraction import ExtractionResult, ObservationDraft, ProblemExtractor, run_extraction
from .ingestion import IngestionResult, ingest
from .prediction_extractor import JsonlPredictionExtractor
from .reporting import OpportunityReport, build_opportunity_report
from .repository import IntegrityError, Repository

__all__ = [
    "BenchmarkCase",
    "BenchmarkPrediction",
    "BenchmarkValidationError",
    "ClaimKind",
    "Competitor",
    "CompetitorComplaint",
    "CompetitorEvidenceRole",
    "CounterEvidenceItem",
    "CounterEvidenceType",
    "ActorEquivalence",
    "ClusteringBenchmarkCase",
    "ClusteringResult",
    "DachAssessment",
    "DachTransferType",
    "EvidenceCitation",
    "EvidenceScope",
    "EvidenceState",
    "ExtractionResult",
    "IngestionResult",
    "IntegrityError",
    "JsonlFileConnector",
    "JsonlPredictionExtractor",
    "LocalEvidenceState",
    "ObservationDraft",
    "ObservationRecord",
    "OpportunityClaimRole",
    "OpportunityRecord",
    "OpportunityReport",
    "OpportunityStatus",
    "OpportunityType",
    "PipelineStage",
    "PipelineStatus",
    "ProblemType",
    "ProblemExtractor",
    "RequirementProgress",
    "RequirementStatus",
    "Repository",
    "ResearchCaseReportData",
    "ResearchCaseStatus",
    "ResearchCaseSummary",
    "ResearchRequirement",
    "SolutionType",
    "SourceLifecycle",
    "SourceConnector",
    "SourceDescriptor",
    "SourceItemInput",
    "SourceItemRecord",
    "WorkflowEquivalence",
    "build_opportunity_report",
    "cluster_exact",
    "evaluate_exact_clustering",
    "evaluate_predictions",
    "ingest",
    "load_benchmark",
    "load_clustering_benchmark",
    "load_predictions",
    "observation_fingerprint",
    "run_extraction",
]
